version: '3.8'
services:
  es01:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.8.2'
    ports:
      - '0.0.0.0:9200:9200'
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: always
    environment:
      - node.name=es01
      - cluster.name=es_local_claster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: 1073741824
    ulimits:
      memlock:
        soft: -1
        hard: -1
volumes:
  esdata:
    driver: local
